version: "3.7"
services:
  dacs-postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dacs
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: